language: generic
sudo: required
services:
  - docker 

before_install: 
  - docker build -t abaulderstone/docker-cra-template -f Dockerfile.dev . 

script: 
  - docker run -e CI=true abaulderstone/docker-cra-template yarn test 


deploy: 
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-cra-template"
  env: "Dockercratemplate-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-183817317903"
  bucket_path: "docker-cra-template"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"